name = "rpdb"
main = "worker.js"
compatibility_date = "2024-02-10"

[[kv_namespaces]]
binding = "USER_KEYS"
id = "f061a15e71f74e69aa21a571f889e05d"

[[d1_databases]]
binding = "POSTER_CACHE"
database_name = "poster-data"
database_id = "64832706-ceb2-4907-a6a2-62c5b197a8fd"

[vars]
FANART_API_KEY="474df0c4626d01344571c33076e628da"
MDBLIST_API_KEY="r5gmzaektnxqnin5kl7iknjny"
TMDB_API_KEY="ba133e792590c9d89882093eea76e13f"

[placement]
mode = "smart"