import type { PosterConfig } from '../types';
import type { MiniPreview } from './tutorialSteps';

export type SimplePresetId =
  | 'cinematic-row'
  | 'streaming-clean'
  | 'minimal-ratings'
  | 'glass-badges';

export interface SimplePreset {
  id: SimplePresetId;
  name: string;
  tagline: string;
  preview: MiniPreview;
  apply: (config: PosterConfig) => PosterConfig;
}

const withSharedIdentity = (current: PosterConfig, next: PosterConfig): PosterConfig => ({
  ...next,
  mediaType: current.mediaType,
  tmdbId: current.tmdbId,
  imdbId: current.imdbId,
  source: current.source,
  ptype: current.ptype,
  textless: current.textless,
  keys: current.keys,
  extension: current.extension,
});

export const simplePresets: SimplePreset[] = [
  {
    id: 'cinematic-row',
    name: 'Cinematic bottom row',
    tagline: 'Trailer-grade lower-third badges with amber glass and big-screen contrast.',
    preview: {
      tone: 'ember',
      layout: 'bottom-row',
      finish: 'glass',
      badges: ['IMDb 8.7', 'RT 73%', 'AUD 91%'],
      title: 'NEON DAWN',
    },
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'b',
        theme: 'glass',
        ratings: ['imdb', 'rt', 'rt_popcorn'],
        layout: 'row',
        preset: 'bc',
        posterBlur: 3,
        grayscale: false,
        blur: 16,
        alpha: 0.52,
        radius: 20,
        shadow: 18,
        scale: 0.88,
        bg: '#0a0704',
        txt: '#fff3dc',
        borderW: 1,
        borderC: '#d79a45',
        icon: true,
        showText: true,
        logo: false,
        minimalTitleEnabled: false,
        minimalRatingsEnabled: false,
        minimalYearEnabled: false,
        minimalDurationEnabled: false,
        items: {},
      }),
  },
  {
    id: 'streaming-clean',
    name: 'Streaming-library clean',
    tagline: 'Premium catalog metadata: sharp, compact, readable from across the room.',
    preview: {
      tone: 'noir-blue',
      layout: 'right-stack',
      finish: 'solid',
      badges: ['IMDb', 'TMDB', 'PG-13', '1h 52m'],
      title: 'AFTER HOURS',
    },
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'b',
        theme: 'solid',
        ratings: ['imdb', 'tmdb', 'age', 'runtime'],
        layout: 'col',
        preset: 'br',
        posterBlur: 0,
        grayscale: false,
        blur: 0,
        alpha: 0.86,
        radius: 12,
        shadow: 10,
        scale: 0.72,
        bg: '#0d1422',
        txt: '#f8fafc',
        borderW: 0,
        borderC: undefined,
        icon: true,
        showText: true,
        normalize: true,
        logo: false,
        minimalTitleEnabled: false,
        minimalRatingsEnabled: false,
        minimalYearEnabled: false,
        minimalDurationEnabled: false,
        items: {},
      }),
  },
  {
    id: 'minimal-ratings',
    name: 'Minimal title + ratings',
    tagline: 'Festival-poster typography with scores treated as restrained editorial details.',
    preview: {
      tone: 'plum',
      layout: 'title-block',
      finish: 'minimal',
      badges: ['★ 8.7', '● 73%', '2024'],
      title: 'THE LONG NIGHT',
    },
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'm',
        theme: 'glass',
        ratings: ['title', 'year', 'imdb', 'rt'],
        layout: 'custom',
        preset: 'custom',
        posterBlur: 0,
        grayscale: false,
        blur: 0,
        alpha: 0.35,
        radius: 12,
        shadow: 6,
        scale: 1,
        bg: undefined,
        txt: '#ffffff',
        borderW: 0,
        icon: true,
        showText: true,
        logo: false,
        minimalTitleEnabled: true,
        minimalTextSize: 58,
        minimalTextX: 28,
        minimalTextY: 615,
        minimalTitleWidth: 420,
        minimalTitleAlign: 'left',
        minimalTitleFlow: 'up',
        minimalTitleColor: '#f8fafc',
        minimalTitleWeight: 800,
        minimalTitleShadowEnabled: true,
        minimalTitleShadowBlur: 18,
        minimalRatingsEnabled: true,
        minimalRatings: [
          {
            provider: 'imdb',
            enabled: true,
            x: 28,
            y: 664,
            size: 24,
            color: '#facc15',
            opacity: 1,
            iconMode: 'star',
            symbol: '★',
            bgEnabled: false,
            bgColor: '#000000',
            bgOpacity: 0,
            borderW: 0,
            borderColor: '#ffffff',
            borderOpacity: 0.7,
            radius: 0,
            paddingX: 0,
            paddingY: 0,
            shadowEnabled: true,
            shadowX: 0,
            shadowY: 2,
            shadowBlur: 10,
            shadowColor: '#000000',
          },
          {
            provider: 'rt',
            enabled: true,
            x: 145,
            y: 664,
            size: 24,
            color: '#fb7185',
            opacity: 1,
            iconMode: 'star',
            symbol: '★',
            bgEnabled: false,
            bgColor: '#000000',
            bgOpacity: 0,
            borderW: 0,
            borderColor: '#ffffff',
            borderOpacity: 0.7,
            radius: 0,
            paddingX: 0,
            paddingY: 0,
            shadowEnabled: true,
            shadowX: 0,
            shadowY: 2,
            shadowBlur: 10,
            shadowColor: '#000000',
          },
        ],
        minimalYearEnabled: true,
        minimalDurationEnabled: true,
        minimalMetaX: 28,
        minimalMetaY: 706,
        minimalDurationX: 118,
        minimalDurationY: 706,
        minimalMetaSize: 18,
        minimalMetaColor: '#d6dde3',
        minimalMetaOpacity: 0.9,
        items: {},
      }),
  },
  {
    id: 'glass-badges',
    name: 'Glass badges',
    tagline: 'Frosted hero chips, white edge light, and a glossy marquee feel.',
    preview: {
      tone: 'silver',
      layout: 'top-ribbon',
      finish: 'glass',
      badges: ['IMDb 8.7', 'RT 73%', 'LB 4.2', 'META 76'],
      title: 'GLASS CITY',
    },
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'b',
        theme: 'glass',
        ratings: ['imdb', 'rt', 'letterboxd', 'meta'],
        layout: 'row',
        preset: 'tc',
        posterBlur: 7,
        grayscale: false,
        blur: 22,
        alpha: 0.36,
        radius: 24,
        shadow: 24,
        scale: 0.78,
        bg: '#ffffff',
        txt: '#ffffff',
        borderW: 1,
        borderC: '#ffffff',
        icon: true,
        showText: true,
        logo: false,
        minimalTitleEnabled: false,
        minimalRatingsEnabled: false,
        minimalYearEnabled: false,
        minimalDurationEnabled: false,
        items: {},
      }),
  },
];

export const getSimplePreset = (id: SimplePresetId): SimplePreset =>
  simplePresets.find((preset) => preset.id === id) ?? simplePresets[0];
