import type { PosterConfig } from '../types';

export type SimplePresetId =
  | 'cinematic-row'
  | 'streaming-clean'
  | 'minimal-ratings'
  | 'glass-badges';

export interface SimplePreset {
  id: SimplePresetId;
  name: string;
  tagline: string;
  previewClass: string;
  apply: (config: PosterConfig) => PosterConfig;
}

const withSharedIdentity = (current: PosterConfig, next: PosterConfig): PosterConfig => ({
  ...next,
  mediaType: current.mediaType,
  tmdbId: current.tmdbId,
  imdbId: current.imdbId,
  source: current.source,
  ptype: current.ptype,
  textless: current.textless,
  keys: current.keys,
  extension: current.extension,
});

export const simplePresets: SimplePreset[] = [
  {
    id: 'cinematic-row',
    name: 'Cinematic bottom row',
    tagline: 'A studio-trailer style row anchored over the lower safe area.',
    previewClass: 'from-[#0b0a09] via-[#34210d] to-[#090807]',
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'b',
        theme: 'glass',
        ratings: ['imdb', 'rt', 'rt_popcorn'],
        layout: 'row',
        preset: 'bc',
        posterBlur: 2,
        grayscale: false,
        blur: 12,
        alpha: 0.5,
        radius: 18,
        shadow: 14,
        scale: 0.9,
        bg: '#080706',
        txt: '#f8ead2',
        borderW: 1,
        borderC: '#d79a45',
        icon: true,
        showText: true,
        logo: false,
        minimalTitleEnabled: false,
        minimalRatingsEnabled: false,
        minimalYearEnabled: false,
        minimalDurationEnabled: false,
        items: {},
      }),
  },
  {
    id: 'streaming-clean',
    name: 'Streaming-library clean',
    tagline: 'Compact, readable badges for Plex/Jellyfin libraries.',
    previewClass: 'from-[#101722] via-[#152235] to-[#05070a]',
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'b',
        theme: 'solid',
        ratings: ['imdb', 'tmdb', 'age', 'runtime'],
        layout: 'col',
        preset: 'br',
        posterBlur: 0,
        grayscale: false,
        blur: 0,
        alpha: 0.78,
        radius: 10,
        shadow: 8,
        scale: 0.72,
        bg: '#10131a',
        txt: '#f8fafc',
        borderW: 0,
        borderC: undefined,
        icon: true,
        showText: true,
        normalize: true,
        logo: false,
        minimalTitleEnabled: false,
        minimalRatingsEnabled: false,
        minimalYearEnabled: false,
        minimalDurationEnabled: false,
        items: {},
      }),
  },
  {
    id: 'minimal-ratings',
    name: 'Minimal title + ratings',
    tagline: 'Typography-first layout with ratings set as quiet metadata.',
    previewClass: 'from-[#17120d] via-[#2a241f] to-[#060504]',
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'm',
        theme: 'glass',
        ratings: ['title', 'year', 'imdb', 'rt'],
        layout: 'custom',
        preset: 'custom',
        posterBlur: 0,
        grayscale: false,
        blur: 0,
        alpha: 0.35,
        radius: 12,
        shadow: 6,
        scale: 1,
        bg: undefined,
        txt: '#ffffff',
        borderW: 0,
        icon: true,
        showText: true,
        logo: false,
        minimalTitleEnabled: true,
        minimalTextSize: 58,
        minimalTextX: 28,
        minimalTextY: 615,
        minimalTitleWidth: 420,
        minimalTitleAlign: 'left',
        minimalTitleFlow: 'up',
        minimalTitleColor: '#f8fafc',
        minimalTitleWeight: 800,
        minimalTitleShadowEnabled: true,
        minimalTitleShadowBlur: 16,
        minimalRatingsEnabled: true,
        minimalRatings: [
          {
            provider: 'imdb',
            enabled: true,
            x: 28,
            y: 664,
            size: 24,
            color: '#facc15',
            opacity: 1,
            iconMode: 'star',
            symbol: '★',
            bgEnabled: false,
            bgColor: '#000000',
            bgOpacity: 0,
            borderW: 0,
            borderColor: '#ffffff',
            borderOpacity: 0.7,
            radius: 0,
            paddingX: 0,
            paddingY: 0,
            shadowEnabled: true,
            shadowX: 0,
            shadowY: 2,
            shadowBlur: 10,
            shadowColor: '#000000',
          },
          {
            provider: 'rt',
            enabled: true,
            x: 145,
            y: 664,
            size: 24,
            color: '#fb7185',
            opacity: 1,
            iconMode: 'star',
            symbol: '★',
            bgEnabled: false,
            bgColor: '#000000',
            bgOpacity: 0,
            borderW: 0,
            borderColor: '#ffffff',
            borderOpacity: 0.7,
            radius: 0,
            paddingX: 0,
            paddingY: 0,
            shadowEnabled: true,
            shadowX: 0,
            shadowY: 2,
            shadowBlur: 10,
            shadowColor: '#000000',
          },
        ],
        minimalYearEnabled: true,
        minimalDurationEnabled: true,
        minimalMetaX: 28,
        minimalMetaY: 706,
        minimalDurationX: 118,
        minimalDurationY: 706,
        minimalMetaSize: 18,
        minimalMetaColor: '#d6dde3',
        minimalMetaOpacity: 0.9,
        items: {},
      }),
  },
  {
    id: 'glass-badges',
    name: 'Glass badges',
    tagline: 'Premium translucent chips with soft highlights.',
    previewClass: 'from-[#111827] via-[#303749] to-[#09090b]',
    apply: (config) =>
      withSharedIdentity(config, {
        ...config,
        uiPreset: 'b',
        theme: 'glass',
        ratings: ['imdb', 'rt', 'letterboxd', 'meta'],
        layout: 'row',
        preset: 'tc',
        posterBlur: 6,
        grayscale: false,
        blur: 18,
        alpha: 0.34,
        radius: 22,
        shadow: 20,
        scale: 0.78,
        bg: '#ffffff',
        txt: '#ffffff',
        borderW: 1,
        borderC: '#ffffff',
        icon: true,
        showText: true,
        logo: false,
        minimalTitleEnabled: false,
        minimalRatingsEnabled: false,
        minimalYearEnabled: false,
        minimalDurationEnabled: false,
        items: {},
      }),
  },
];

export const getSimplePreset = (id: SimplePresetId): SimplePreset =>
  simplePresets.find((preset) => preset.id === id) ?? simplePresets[0];
