// src/pages/dashboard/components/LiveDemo.tsx
import React, { useState } from 'react';
import FadeSection from './FadeSection';
import BadgeChip from './BadgeChip';
import { DEMO_CONFIGS, BADGE_DATA, POSTERS } from '../data';
import { buildPosterUrl } from '../utils';

const LiveDemo: React.FC = () => {
  const [active, setActive] = useState(0);
  const cfg = DEMO_CONFIGS[active];

  return (
    <section id="demo" className="py-20 sm:py-28 px-4 sm:px-6">
      <div className="max-w-6xl mx-auto">
        {/* Heading */}
        <FadeSection>
          <div className="text-center mb-12 sm:mb-16">
            <p className="text-[11px] font-bold text-indigo-400 uppercase tracking-[0.15em] mb-3">Live Previews</p>
            <h2 className="text-3xl sm:text-4xl font-black text-white mb-4">Real posters. Real ratings.</h2>
            <p className="text-[13px] sm:text-[14px] text-zinc-600 max-w-md mx-auto">
              Every image below is generated by the API in real-time with live rating data.
            </p>
          </div>
        </FadeSection>

        {/* Preset tabs */}
        <FadeSection delay={100}>
          <div className="flex flex-wrap items-center justify-center gap-2 mb-8">
            {DEMO_CONFIGS.map((d, i) => (
              <button
                key={i}
                onClick={() => setActive(i)}
                className={`px-3 sm:px-4 py-2 rounded-xl text-[11px] sm:text-[12px] font-semibold transition-all border ${
                  active === i
                    ? 'bg-indigo-500/15 text-indigo-300 border-indigo-500/30 shadow-lg shadow-indigo-500/10'
                    : 'text-zinc-600 border-white/[0.06] hover:text-zinc-300 hover:bg-white/5'
                }`}
              >
                {d.label}
              </button>
            ))}
          </div>
        </FadeSection>

        {/* Featured poster + info */}
        <FadeSection delay={150}>
          <div className="flex flex-col lg:flex-row gap-6 sm:gap-8 items-center">
            {/* Poster */}
            <div
              className="relative flex-shrink-0"
              key={`demo-${active}`}
              style={{ animation: 'posterReveal 0.4s cubic-bezier(0.16,1,0.3,1) both' }}
            >
              <div
                className="relative rounded-2xl overflow-hidden shadow-2xl border border-white/10"
                style={{
                  width: 'min(280px, 80vw)',
                  aspectRatio: '2/3',
                  boxShadow: `0 32px 80px rgba(0,0,0,0.8), 0 0 60px ${cfg.poster.accent}20, 0 0 0 1px rgba(255,255,255,0.06)`,
                }}
              >
                <img
                  key={buildPosterUrl(cfg.poster)}
                  src={buildPosterUrl(cfg.poster)}
                  alt={cfg.poster.title}
                  loading="lazy"
                  className="w-full h-full object-cover"
                />
              </div>
              {/* Glow */}
              <div
                className="absolute -inset-4 rounded-3xl blur-2xl -z-10 opacity-20"
                style={{ background: cfg.poster.accent }}
              />
            </div>

            {/* Meta + badges */}
            <div className="flex-1 min-w-0 w-full">
              <div className="mb-4">
                <p
                  className="text-[11px] font-bold uppercase tracking-widest mb-1"
                  style={{ color: cfg.poster.accent }}
                >
                  {cfg.label}
                </p>
                <h3 className="text-xl sm:text-2xl font-black text-white">{cfg.poster.title}</h3>
                <p className="text-[12px] text-zinc-600 mt-1">{cfg.desc}</p>
              </div>

              {/* Badge chips */}
              <div className="flex flex-wrap gap-1.5 mb-6">
                {cfg.poster.badges.split(',').map(b => {
                  const bd = BADGE_DATA.find(x => x.id === b);
                  return bd ? <BadgeChip key={b} badge={bd} /> : null;
                })}
              </div>

              {/* Secondary poster grid */}
              <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-700 mb-2">More posters</p>
              <div className="grid grid-cols-4 sm:grid-cols-6 gap-2">
                {POSTERS.slice(0, 6)
                  .filter(p => p.id !== cfg.poster.id)
                  .slice(0, 5)
                  .map((p, i) => (
                    <div
                      key={p.id}
                      className="relative rounded-lg overflow-hidden aspect-[2/3] bg-zinc-900 border border-white/[0.06] hover:scale-105 transition-transform cursor-default"
                      style={{ animationDelay: `${i * 0.06}s` }}
                    >
                      <img
                        src={buildPosterUrl(p, 'sm')}
                        alt={p.title}
                        loading="lazy"
                        className="w-full h-full object-cover"
                      />
                    </div>
                  ))}
              </div>
            </div>
          </div>
        </FadeSection>
      </div>
    </section>
  );
};

export default LiveDemo;